// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VictoryCloudApi.Data;

#nullable disable

namespace VictoryCloudApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260616115110_updateuploaddate")]
    partial class updateuploaddate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VictoryCloudApi.Models.Art", b =>
                {
                    b.Property<int>("ArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Links")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtId");

                    b.ToTable("Art");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.Comic", b =>
                {
                    b.Property<int>("ComicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComicId"));

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ComicId");

                    b.ToTable("Comics");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.ComicChapter", b =>
                {
                    b.Property<int>("ComicChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComicChapterId"));

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ComicId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ComicChapterId");

                    b.HasIndex("ComicId");

                    b.ToTable("ComicChapters");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.ComicDetails", b =>
                {
                    b.Property<int>("ComicDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComicDetailsId"));

                    b.Property<int>("ComicId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentRating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ComicDetailsId");

                    b.HasIndex("ComicId")
                        .IsUnique();

                    b.ToTable("ComicDetails");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommentMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ContentId")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("WritingId")
                        .HasColumnType("integer");

                    b.HasKey("CommentId");

                    b.HasIndex("WritingId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.Config", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("ConfigItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigItemValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConfigId");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSignInDate")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.Writing", b =>
                {
                    b.Property<int>("WritingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WritingId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Links")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WritingId");

                    b.ToTable("Writing");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.WritingChapter", b =>
                {
                    b.Property<int>("WritingChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WritingChapterId"));

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingChapterTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WritingId")
                        .HasColumnType("integer");

                    b.HasKey("WritingChapterId");

                    b.HasIndex("WritingId");

                    b.ToTable("WritingChapter");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.WritingChapterContent", b =>
                {
                    b.Property<int>("WritingChapterContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WritingChapterContentId"));

                    b.Property<int>("WritingChapterId")
                        .HasColumnType("integer");

                    b.Property<int>("WritingContentPosition")
                        .HasColumnType("integer");

                    b.Property<string>("WritingContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WritingChapterContentId");

                    b.HasIndex("WritingChapterId");

                    b.ToTable("WritingChapterContent");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.WritingChapterContentBlock", b =>
                {
                    b.Property<int>("WritingChapterContentBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WritingChapterContentBlockId"));

                    b.Property<int>("WritingChapterContentId")
                        .HasColumnType("integer");

                    b.Property<string>("WritingContentBlockAltText")
                        .HasColumnType("text");

                    b.Property<string>("WritingContentBlockContent")
                        .HasColumnType("text");

                    b.Property<string>("WritingContentBlockImageUrl")
                        .HasColumnType("text");

                    b.HasKey("WritingChapterContentBlockId");

                    b.HasIndex("WritingChapterContentId");

                    b.ToTable("WritingChapterContentBlock");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.ComicChapter", b =>
                {
                    b.HasOne("VictoryCloudApi.Models.Comic", "Comic")
                        .WithMany("Chapters")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.ComicDetails", b =>
                {
                    b.HasOne("VictoryCloudApi.Models.Comic", "Comic")
                        .WithOne("Details")
                        .HasForeignKey("VictoryCloudApi.Models.ComicDetails", "ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.Comment", b =>
                {
                    b.HasOne("VictoryCloudApi.Models.Writing", null)
                        .WithMany("Comments")
                        .HasForeignKey("WritingId");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.WritingChapter", b =>
                {
                    b.HasOne("VictoryCloudApi.Models.Writing", null)
                        .WithMany("Chapters")
                        .HasForeignKey("WritingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VictoryCloudApi.Models.WritingChapterContent", b =>
                {
                    b.HasOne("VictoryCloudApi.Models.WritingChapter", null)
                        .WithMany("WritingChapterContent")
                        .HasForeignKey("WritingChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VictoryCloudApi.Models.WritingChapterContentBlock", b =>
                {
                    b.HasOne("VictoryCloudApi.Models.WritingChapterContent", null)
                        .WithMany("WritingContentBlock")
                        .HasForeignKey("WritingChapterContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VictoryCloudApi.Models.Comic", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("VictoryCloudApi.Models.Writing", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.WritingChapter", b =>
                {
                    b.Navigation("WritingChapterContent");
                });

            modelBuilder.Entity("VictoryCloudApi.Models.WritingChapterContent", b =>
                {
                    b.Navigation("WritingContentBlock");
                });
#pragma warning restore 612, 618
        }
    }
}
